title: Lighthouse Documentation
description: Documentation for Lighthouse.
theme: just-the-docs

url: https://docs.lighthouse.letpeople.work

logo: "/assets/Logo.png"
color_scheme: dark

search_enabled: true
nav_enabled: true
heading_anchors: true
aux_links_new_tab: true

aux_links:
  Let People Work: https://letpeople.work
  GitHub: https://github.com/letpeoplework/lighthouse
