title: Lighthouse Documentation
description: Documentation for Lighthouse.
theme: just-the-docs

url: https://letpeoplework.github.io/lighthouse

aux_links:
  Template Repository: https://letpeoplework.github.io/lighthouse
