title: Lighthouse Documentation
description: Documentation for Lighthouse.
theme: just-the-docs

url: https://docs.lighthouse.letpeople.work

logo: "/assets/Logo.png"
color_scheme: dark

search_enabled: true
nav_enabled: true
heading_anchors: true
aux_links_new_tab: true

enable_copy_code_button: true

mermaid:
  version: "11.4.1"

livereload: true
force_polling: true

callouts:
  note:
    title: Note
    color: yellow

aux_links:
  Let People Work: https://letpeople.work
  GitHub: https://github.com/letpeoplework/lighthouse
