name: Playwright Tests
description: Run Playwright tests

inputs:
  base-url:
    description: 'The URL of the application to test'
    required: true
    type: string
  run-command:
    description: 'The command to start Lighthouse before running the tests'
    required: true
    type: string


runs:
  using: "composite"    
  steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ./Lighthouse.EndToEndTests

    - name: Install Chromium
      run: npx playwright install chromium --with-deps
      shell: bash
      working-directory: ./Lighthouse.EndToEndTests

    - name: Run Playwright tests
      run: |
        ${{ inputs.run-command }}

        cd ./Lighthouse.EndToEndTests
        npx playwright test
      shell: bash
      env:
        LIGHTHOUSEURL: ${{ inputs.base-url }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./Lighthouse.EndToEndTests/playwright-report/
        retention-days: 30