name: Playwright Tests
description: Run Playwright tests

inputs:
  base-url:
    description: 'The URL of the application to test'
    required: true
    type: string


runs:
  using: "composite"    
  steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ./Lighthouse.EndToEndTests

    - name: Install Chromium
      run: npx playwright install chromium --with-deps
      shell: bash
      working-directory: ./Lighthouse.EndToEndTests

    - name: Wait for Lighthouse to start
      run: |
        echo "Waiting for server to be ready..."
        timeout 30 bash -c 'until curl --silent --fail ${{ inputs.base-url }}; do sleep 1; done'
        echo "Server is ready!"
      shell: bash

    - name: Run Playwright tests
      run: npx playwright test
      shell: bash
      working-directory: ./Lighthouse.EndToEndTests
      env:
        LIGHTHOUSEURL: ${{ inputs.base-url }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ./Lighthouse.EndToEndTests/playwright-report/
        retention-days: 30