name: Build And Deploy Lighthouse

env:
  DOTNET_VERSION: '8'  
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AzureDevOpsLighthouseIntegrationTestToken: ${{ secrets.AZUREDEVOPSLIGHTHOUSEINTEGRATIONTESTTOKEN }}
  JiraLighthouseIntegrationTestToken: ${{ secrets.JIRALIGHTHOUSEINTEGRATIONTESTTOKEN }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Remove Frontend sonar-project.properties
      run: |
        rm ./Lighthouse.Frontend/sonar-project.properties

    - name: Backend Build Test SonarCloud
      uses: highbyte/sonarscan-dotnet@v2.3.1
      with:
        sonarProjectKey: LetPeopleWork_Lighthouse
        sonarProjectName:  Lighthouse.Backend
        sonarOrganization: letpeoplework
        dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
  
  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Install npm dependencies
      run: npm install
      working-directory: ./Lighthouse.Frontend

    - name: Lint Frontend
      run: npm run lint
      working-directory: ./Lighthouse.Frontend

    - name: Build Frontend
      run: npm run build
      working-directory: ./Lighthouse.Frontend

    - name: Test Frontend
      run: npm test
      working-directory: ./Lighthouse.Frontend

    - name: Frontend SonarCloud
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      working-directory: ./Lighthouse.Frontend
      run: |
        npm install -g sonarqube-scanner
        sonar-scanner
        
  docker:
    runs-on: ubuntu-latest
    #needs:
    #- backend
    #- frontend

    #if: github.ref == 'refs/heads/main'

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master        
        with:
          image_name: ${{ github.repository }} 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Lighthouse.Backend/Dockerfile
        

  deploy:
    runs-on: ubuntu-latest
    needs:
    - backend
    - frontend

    if: github.ref == 'refs/heads/main'   

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      contents: write
      id-token: write

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_ROOT}}

      - name: Install npm dependencies
        run: npm install
        working-directory: ./Lighthouse.Frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ./Lighthouse.Frontend

      - name: Create tag if necessary
        id: version
        uses: fregante/daily-version-action@v2
        with:
          prefix: v

      - name: Update appsettings.json
        run: jq '.LighthouseVersion = env.DAILY_VERSION' appsettings.json > temp.json && mv temp.json appsettings.json
        working-directory: ./Lighthouse.Backend

      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./Lighthouse.Backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: Lighthouse ${{ env.DAILY_VERSION }}
          path: ./Lighthouse.Backend/publish

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8A96BB1E9EB043EE9CB0B648544834B0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D622DE733434D3A987E82D0DBCEE2B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6A0B9B55694C47F4A1D8CEA847E84D78 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp  
        uses: azure/webapps-deploy@v2  
        with:  
          app-name: 'LighthouseCloudDemo'  
          slot-name: 'production'  
          package: ./Lighthouse.Backend/publish
      
    outputs:
      created: ${{ steps.version.outputs.created }}
      version: ${{ steps.version.outputs.version }}
  
  release:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'   

    environment:
      name: Release

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master        
        with:
          image_name: ${{ github.repository }} 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Lighthouse.Backend/Dockerfile
          image_tag: ${{ needs.deploy.outputs.version }}

      - uses: actions/download-artifact@v4
        with:
          name: Lighthouse ${{ needs.deploy.outputs.version }}
          path: LighthouseArtifacts

      - uses: vimtor/action-zip@v1.2
        with:
          files: LighthouseArtifacts
          dest: Lighthouse ${{ needs.deploy.outputs.version }}.zip

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Lighthouse ${{ needs.deploy.outputs.version }}.zip"
          tag: ${{ needs.deploy.outputs.version }}
          prerelease: true
          name: "Lighthouse ${{ needs.deploy.outputs.version }}"