name: Slackbot on release

on:
  release:
    types: [published]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Release
    if: github.event.release.prerelease == false
    
    steps:
      - uses: actions/checkout@v4

      - name: Notify Slack on Releases
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚀 New Lighthouse published: *${{ github.event.release.tag_name }}*\n\n${{ github.event.release.body }}"
