name: Update Screenshots For Documentation

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    AzureDevOpsLighthouseIntegrationTestToken: ${{ secrets.AZUREDEVOPSLIGHTHOUSEINTEGRATIONTESTTOKEN }}
    JiraLighthouseIntegrationTestToken: ${{ secrets.JIRALIGHTHOUSEINTEGRATIONTESTTOKEN }}
    AzureDevOpsLighthouseE2ETestToken: ${{secrets.AZUREDEVOPSLIGHTHOUSEE2ETESTTOKEN}}
on:
  workflow_run:
    workflows: ["Build And Deploy Lighthouse"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    name: Recreate and upload new Screenshots
    permissions: write-all
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            LATEST_TAG=$(git describe --tags --abbrev=0)
            echo "VERSION=${LATEST_TAG#v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=dev-latest" >> $GITHUB_OUTPUT
          fi

      - name: Install E2E dependencies
        run: npm ci
        shell: bash
        working-directory: ./Lighthouse.EndToEndTests
  
      - name: Install Chromium
        run: npx playwright install chromium --with-deps
        shell: bash
        working-directory: ./Lighthouse.EndToEndTests

      - name: Run Lighthouse ${{ steps.version.outputs.VERSION }}
        run: docker run -p 5001:5001 -d --name lighthouse --restart always ghcr.io/letpeoplework/lighthouse:${{ steps.version.outputs.VERSION }}
        working-directory: ./Lighthouse.Backend

      - name: Wait for Lighthouse to start
        run: |
          echo "Waiting for server to be ready..."
          timeout 30 bash -c 'until curl --silent --fail --insecure https://localhost:5001; do sleep 1; done'
          echo "Server is ready!"
      
      - name: Recreating Screenshot using Playwright
        run: npm run screenshots
        shell: bash
        working-directory: ./Lighthouse.EndToEndTests
        env:
          LIGHTHOUSEURL: https://localhost:5001

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "Update screenshots for version ${{ steps.version.outputs.VERSION }}"
            title: "Update screenshots for Documentation"
            body: |
                ## Description
                Automated PR to update documentation screenshots.
                
                * Version: ${{ steps.version.outputs.VERSION }}
                * Triggered by: ${{ github.event_name }}
            branch: docs/update-screenshots-${{ steps.version.outputs.VERSION }}
            base: main
            delete-branch: true
            labels: |
                documentation
                automated pr
            draft: false